#!/bin/sh
set -eu

THIS_FILE=$(readlink -f "$0")
BASEDIR=$(dirname "$THIS_FILE")

NDK="26.1.10909125"

version_format='([0-9\.]+)'

expression="s/ndk-$version_format/ndk-$NDK/"
sed -E "--expression=$expression" -i $BASEDIR/README.md

expression="s/ndkVersion '$version_format'/ndkVersion '$NDK'/"
sed -E "--expression=$expression" -i $BASEDIR/wvWare/build.gradle $BASEDIR/dependency-builder/build.gradle
